// @generated by protoc-gen-es v2.3.0 with parameter "target=ts"
// @generated from file SpaghettiCannon/clientapi/v1/clientapi.proto (package SpaghettiCannon.clientapi.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file SpaghettiCannon/clientapi/v1/clientapi.proto.
 */
export const file_SpaghettiCannon_clientapi_v1_clientapi: GenFile = /*@__PURE__*/
  fileDesc("CixTcGFnaGV0dGlDYW5ub24vY2xpZW50YXBpL3YxL2NsaWVudGFwaS5wcm90bxIcU3BhZ2hldHRpQ2Fubm9uLmNsaWVudGFwaS52MSISChBHZXRSZWFkeXpSZXF1ZXN0IjYKEUdldFJlYWR5elJlc3BvbnNlEhAKCGlzX3JlYWR5GAEgASgIEg8KB3ZlcnNpb24YAiABKAkiIwoQQWRkVXBkYXRlUmVxdWVzdBIPCgdjb250ZW50GAEgASgJIhMKEUFkZFVwZGF0ZVJlc3BvbnNlMvsBChlTcGFnaGV0dGlDYW5ub25BcGlTZXJ2aWNlEm4KCUdldFJlYWR5ehIuLlNwYWdoZXR0aUNhbm5vbi5jbGllbnRhcGkudjEuR2V0UmVhZHl6UmVxdWVzdBovLlNwYWdoZXR0aUNhbm5vbi5jbGllbnRhcGkudjEuR2V0UmVhZHl6UmVzcG9uc2UiABJuCglBZGRVcGRhdGUSLi5TcGFnaGV0dGlDYW5ub24uY2xpZW50YXBpLnYxLkFkZFVwZGF0ZVJlcXVlc3QaLy5TcGFnaGV0dGlDYW5ub24uY2xpZW50YXBpLnYxLkFkZFVwZGF0ZVJlc3BvbnNlIgBCTlpMZ2l0aHViLmNvbS9qYW1lc3JlYWQvU3BhZ2hldHRpQ2Fubm9uL2dlbi9TcGFnaGV0dGlDYW5ub24vY2xpZW50YXBpL3YxO3NwYWd2MWIGcHJvdG8z");

/**
 * @generated from message SpaghettiCannon.clientapi.v1.GetReadyzRequest
 */
export type GetReadyzRequest = Message<"SpaghettiCannon.clientapi.v1.GetReadyzRequest"> & {
};

/**
 * Describes the message SpaghettiCannon.clientapi.v1.GetReadyzRequest.
 * Use `create(GetReadyzRequestSchema)` to create a new message.
 */
export const GetReadyzRequestSchema: GenMessage<GetReadyzRequest> = /*@__PURE__*/
  messageDesc(file_SpaghettiCannon_clientapi_v1_clientapi, 0);

/**
 * @generated from message SpaghettiCannon.clientapi.v1.GetReadyzResponse
 */
export type GetReadyzResponse = Message<"SpaghettiCannon.clientapi.v1.GetReadyzResponse"> & {
  /**
   * @generated from field: bool is_ready = 1;
   */
  isReady: boolean;

  /**
   * @generated from field: string version = 2;
   */
  version: string;
};

/**
 * Describes the message SpaghettiCannon.clientapi.v1.GetReadyzResponse.
 * Use `create(GetReadyzResponseSchema)` to create a new message.
 */
export const GetReadyzResponseSchema: GenMessage<GetReadyzResponse> = /*@__PURE__*/
  messageDesc(file_SpaghettiCannon_clientapi_v1_clientapi, 1);

/**
 * @generated from message SpaghettiCannon.clientapi.v1.AddUpdateRequest
 */
export type AddUpdateRequest = Message<"SpaghettiCannon.clientapi.v1.AddUpdateRequest"> & {
  /**
   * @generated from field: string content = 1;
   */
  content: string;
};

/**
 * Describes the message SpaghettiCannon.clientapi.v1.AddUpdateRequest.
 * Use `create(AddUpdateRequestSchema)` to create a new message.
 */
export const AddUpdateRequestSchema: GenMessage<AddUpdateRequest> = /*@__PURE__*/
  messageDesc(file_SpaghettiCannon_clientapi_v1_clientapi, 2);

/**
 * @generated from message SpaghettiCannon.clientapi.v1.AddUpdateResponse
 */
export type AddUpdateResponse = Message<"SpaghettiCannon.clientapi.v1.AddUpdateResponse"> & {
};

/**
 * Describes the message SpaghettiCannon.clientapi.v1.AddUpdateResponse.
 * Use `create(AddUpdateResponseSchema)` to create a new message.
 */
export const AddUpdateResponseSchema: GenMessage<AddUpdateResponse> = /*@__PURE__*/
  messageDesc(file_SpaghettiCannon_clientapi_v1_clientapi, 3);

/**
 * @generated from service SpaghettiCannon.clientapi.v1.SpaghettiCannonApiService
 */
export const SpaghettiCannonApiService: GenService<{
  /**
   * @generated from rpc SpaghettiCannon.clientapi.v1.SpaghettiCannonApiService.GetReadyz
   */
  getReadyz: {
    methodKind: "unary";
    input: typeof GetReadyzRequestSchema;
    output: typeof GetReadyzResponseSchema;
  },
  /**
   * @generated from rpc SpaghettiCannon.clientapi.v1.SpaghettiCannonApiService.AddUpdate
   */
  addUpdate: {
    methodKind: "unary";
    input: typeof AddUpdateRequestSchema;
    output: typeof AddUpdateResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_SpaghettiCannon_clientapi_v1_clientapi, 0);
