project_name: SpaghettiCannon
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux

    goarch:
      - amd64
      - arm64

    main: main.go

    dir: service

    ldflags:
      - >
        -s -w
        -X github.com/jamesread/SpaghettiCannon/internal/buildinfo.Version={{.Version}}
        -X github.com/jamesread/SpaghettiCannon/internal/buildinfo.GitCommit={{.Commit}}
        -X github.com/jamesread/SpaghettiCannon/internal/buildinfo.BuildDate={{.Date}}

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Branch }}-{{ .ShortCommit }}"
changelog:
  sort: asc
  groups:
    - title: 'Security'
      regexp: '^.*?security(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Features'
      regexp: '^.*?feature(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Bug fixes'
      regexp: '^.*?bugfix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^cicd:'
      - '^refactor:'

archives: []

dockers:
  - image_templates:
      - "ghcr.io/jamesread/spaghetticannon:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    skip_push: false
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Tag}}"
    extra_files:
      - frontend
      - config.yaml

  - image_templates:
      - "ghcr.io/jamesread/spaghetticannon:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    goos: linux
    goarch: arm64
    skip_push: false
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Tag}}"
    extra_files:
      - frontend
      - config.yaml


docker_manifests:
  - name_template: ghcr.io/jamesread/spaghetticannon:latest
    image_templates:
      - ghcr.io/jamesread/spaghetticannon:{{ .Version }}-amd64
      - ghcr.io/jamesread/spaghetticannon:{{ .Version }}-arm64

release:
  footer: |
    ## Container images (from GitHub)

    - `docker pull ghcr.io/jamesread/spaghetticannon:{{ .Version }}`

    ## Upgrade warnings, or breaking changes

    - No such issues between the last release and this version.

    Thanks for your interest in SpaghettiCannon!
