---
name: "Build Snapshot"

on:
  - push
  - workflow_dispatch

jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64

      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22.0'
          go-version-file: 'backend/go.mod'
          cache: true

      - name: make protoc
        run: make -w protoc

      - name: make backend
        run: make -w backend

      - name: make frontend
        run: make -w frontend

#      - name: integration tests
#        run: cd integration-tests && make -w

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean --skip=docker

      - name: get date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: Archive binaries
        uses: actions/upload-artifact@v4.3.1
        with:
          name: "SpaghettiCannon-snapshot-${{ env.DATE }}-${{ github.sha }}"
          path: dist/SpaghettiCannon*.*

            #      - name: Archive integration tests
            #        uses: actions/upload-artifact@v4.3.1
            #        with:
            #          name: "SpaghettiCannon-integration-tests-${{ env.DATE }}-${{ github.sha }}"
            #          path: |
            #            integration-tests
            #            !integration-tests/node_modules
