---
name: "Build Tag"

on:
  push:
    tags:
      - '*'

jobs:
  build-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: webui.dev/package-lock.json

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.18.0'
          cache: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_TOKEN }}

      - name: grpc
        run: make -w grpc

      - name: make webui
        run: make -w webui-dist

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --parallelism 1
        env:
          GITHUB_TOKEN: ${{ secrets.CONTAINER_TOKEN }}

      - name: Archive binaries
        uses: actions/upload-artifact@v4.3.1
        with:
          name: "SpaghettiCannon-${{ github.ref_name }}"
          path: dist/SpaghettiCannon*.*

      - name: Archive integration tests
        uses: actions/upload-artifact@v4.3.1
        with:
          name: integration-tests
          path: |
            integration-tests
            !integration-tests/node_modules
